package adminui;

import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;
import operations.Validations;
import project.dao.LoginInfoDAO;
import project.to.LoginInfoTO;
import utility.CommonOperations;

public class AddNewStudent extends javax.swing.JInternalFrame {

    private String username;

    public AddNewStudent() {
        initComponents();
        getRootPane().setDefaultButton(btnAdd);
    }

    public AddNewStudent(String username) {
        this();
        LoginInfoTO record = new LoginInfoDAO().getRecord(username);
        if (record != null) {
            this.username = username;
            setTitle("Update Student Details");
            btnAdd.setText("Update Student Details");
            jtfUsername.setText(record.getUsername());
            jpfPassword.setText(record.getPassword());
            jtfRolename.setText(record.getRolename());
            jtfUsername.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jtfRolename = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jpfPassword = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Test Engine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 1, 12))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Student Details");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter User Name :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter Role Name :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Enter Password :");

        jtfUsername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtfRolename.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfRolename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfRolenameKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAdd.setText("Add New Student");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jpfPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfUsername)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addComponent(jtfRolename)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRolename, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = "";
        boolean allvalid = true;
        String username = jtfUsername.getText().trim();
        String password = jpfPassword.getText().trim();
        String rolename = jtfRolename.getText().trim();
        if (Validations.isEmpty(username)) {
            allvalid = false;
            message += "Please Enter UserName\n\n";
        } else if (!Validations.onlyCharacter(username)) {
            allvalid = false;
            message += "Please Enter Character Value in UserName Box\n\n";
        }
        if (Validations.isEmpty(password)) {
            allvalid = false;
            message += "Please Enter Password\n\n";
        }
        if (Validations.isEmpty(rolename)) {
            allvalid = false;
            message += "Please Enter Any RoleName\n\n";
        } else if (!Validations.onlyCharacter(rolename)) {
            allvalid = false;
            message += "Please Enter Character Value in RoleName Box\n\n";
        }
        if (allvalid) {
            LoginInfoTO record = new LoginInfoTO();
            record.setUsername(username);
            record.setPassword(password);
            record.setRolename(rolename);
            LoginInfoDAO action = new LoginInfoDAO();
            if (btnAdd.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    message = "New Student Record is Added in System";
                } else {
                    if (action.getErrormessage().contains("key")) {
                        message = "Primary Key Failure\n\nAttempt for Duplicate Entry ";
                    } else {
                        message = "Insertion Failure Due TO " + action.getErrormessage();
                    }
                }
            } else if (btnAdd.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    message = "Student Details is Updated in System";
                } else {
                    if (action.getErrormessage().contains("foreign")) {
                        message = "Foreign Key Failure\n\nAttempt to Update Primary Row ";
                    } else {
                        message = "Updation Failure Due TO " + action.getErrormessage();
                    }
                }
                CommonOperations.showScreen(getDesktopPane(), new ViewStudentDetails());
                dispose();
            } else {
                message = "There is No Default Operations";
            }
        }

        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfRolenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRolenameKeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfRolenameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfRolename;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
