/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import project.dao.SectionInfoDAO;
import project.to.SectionInfoTO;
import utility.CommonOperations;

/**
 *
 * @author HP
 */
public class ViewSectionDetails extends javax.swing.JInternalFrame {

    List<SectionInfoTO> secinfo;
    private JPopupMenu popupmenu;
    int sectionid;

    public ViewSectionDetails() {
        initComponents();
        bindTables();
        popupmenu = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete This Record");
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/delete.png"));
            deleteitem.setIcon(icon);
        } catch (Exception ex) {
        }
        popupmenu.add(deleteitem);
        JMenuItem edititem = new JMenuItem("Edit This Record");
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/update1.png"));
            edititem.setIcon(icon);
        } catch (Exception ex) {
        }
        popupmenu.add(edititem);
        deleteitem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleterecord();
            }
        });
        edititem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editrecord();
            }
        });
    }

    public void editrecord() {
        if (sectionid != 0) {
            CommonOperations.showScreen(getDesktopPane(), new AddNewSection(sectionid));
            dispose();
        }
        sectionid = 0;
    }

    public void deleterecord() {
        if (sectionid != 0) {
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Delete This Record?", "Message From System", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                SectionInfoDAO action = new SectionInfoDAO();
                String message = "";
                if (action.deleteRecord(sectionid)) {
                    message = "Record is Removed From DataBase";
                    bindTables();
                } else {
                    if (action.getErrormessage().contains("foreign")) {
                        message = "Foreign Key Failure\n\nAttempt to Delete Primary Row ";
                    } else {
                        message = "Deletion Failure Due TO " + action.getErrormessage();
                    }
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        sectionid = 0;
    }

    public void bindTables() {
        secinfo = new SectionInfoDAO().getAllRecord();
        String colnames[] = {"Section ID", "Section Name", "Subject ID", "Marks"};
        Object[][] records = null;
        if (secinfo != null && secinfo.size() > 0) {
            records = new Object[secinfo.size()][colnames.length];
            int i = 0;
            for (SectionInfoTO sct : secinfo) {
                records[i] = new Object[]{sct.getSectionid(), sct.getSectionname(), sct.getSubjectid(), sct.getMarks()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"No Records", "No Records", "No Records", "No Records"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, colnames);
        tableSection.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSection = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Section Details");

        tableSection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSectionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSection);

        btnLoad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnLoad.setText("Load Again");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        bindTables();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void tableSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSectionMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            int rowatpoint = tableSection.rowAtPoint(evt.getPoint());
            tableSection.getSelectionModel().setSelectionInterval(rowatpoint, rowatpoint);
            popupmenu.show(tableSection, evt.getX(), evt.getY());
            int srow = tableSection.getSelectedRow();
            sectionid = Integer.parseInt(tableSection.getValueAt(srow, 0).toString());
        }
    }//GEN-LAST:event_tableSectionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSection;
    // End of variables declaration//GEN-END:variables
}
